### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by Col-E** [Col-E/Code2HTML#3]
Future updates will allow more than only java to be style-matched.

So **Java**2HTML now is more like **AnythingYouHaveRegexFor**2HTML, but a better name has to exist. Would like to hear some options. For now, the deceptive name can be kept.

Or, this may be a dumb idea and the name should be kept. I'd like to hear some opinions on the matter.

**Comment by foures** [comment]
You maybe could name it **Code2HTML** ?

**Comment by Col-E** [comment]
Considering [`3.3.0`](https://github.com/Col-E/Code2HTML/releases/tag/3.3.0) bringing `CSS` as a supported language _(Making it so that java is not the only default language supported)_, the suggestion for `Code2HTML` has been accepted
